# Site settings
title: Tableau UI
email: git@tableau.com
description: Create React components which have the look-and-feel of Tableau.
baseurl: "/tableau-ui"
# permalink: pretty

defaults:
  -
    scope:
      path: "" # Apply to all files
      type: pages
    values:
      layout: "default"
      permalink: /:path/:basename:output_ext

# Build settings
markdown: kramdown
highlighter: rouge
github: [metadata]

kramdown:
    toc_levels: 1..3

# Exclude
exclude: ['node_modules', 'Examples']
